# Generated by Django 4.0.1 on 2022-01-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cons',
            options={'verbose_name': 'Концентрат'},
        ),
        migrations.AddField(
            model_name='cons',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Наименование сырья'),
            preserve_default=False,
        ),
    ]
