# Generated by Django 4.0.1 on 2022-01-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cons_options_cons_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cons',
            new_name='Conс',
        ),
        migrations.AlterModelOptions(
            name='conс',
            options={'verbose_name': 'Концентрат', 'verbose_name_plural': 'Концентраты'},
        ),
    ]
